from ..exceptions import ValidationError

# TODO: user validator
def username_validator(username):

    return True

def email_validator(email):
    return True


#TODO: task validator
def task_validator(task):
    return True

def subtask_validator(subtask):
    return True


#TODO: group validator
def group_validator(group):
    return True